name: "Terragrunt Temp Environment Deploy"
description: "Creates a temporary environment via Terragrunt/Terraform"
author: "Mitchell"
runs:
  using: "node12"
  main: "main.js"
branding:
  icon: upload-cloud
  color: green
